package com.javaauto.demo;

import org.springframework.boot.CommandLineRunner;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.beans.factory.annotation.Autowired;

@SpringBootApplication
public class DemoApplication implements CommandLineRunner{
	@Autowired // This means to get the bean called playerRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	private PlayerRepository playerRepository;

	public void AddPlayer()
	{
		Player player = new Player();
		player.setJerseyNumber(13);
		player.setName("Mats Sundin");

		playerRepository.save(player);
	} 

	@Override
    public void run(String... args) {
		while(true)
		{
			System.out.println("1. Ny player");
			System.out.println("Input:>");
			int selection = Integer.parseInt(System.console().readLine());
			if(selection == 1)
				AddPlayer();
		}
    }
	public static void main(String[] args) {
		SpringApplication.run(DemoApplication.class, args);
	}

}
